spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.255.128:8848

server:
  port: 10101

dubbo:
  application:
    name: provider
  protocol:
    name: dubbo
    port: -1
    serialization: kryo
  provider:
    loadbalance: roundrobin
  registry:
    address: nacos://192.168.255.128:8848
  scan:
    base-packages: com.funtl.alibaba.dubbo.provider.service

management:
  endpoints:
    web:
      exposure:
        include: "*"
