spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: consumer
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.255.128:8848

server:
  port: 10201

dubbo:
  application:
    name: consumer
    qos-enable: false
  protocol:
    name: dubbo
    port: -1
    serialization: kryo
  registry:
    address: nacos://192.168.255.128:8848
  scan:
    base-packages: com.funtl.alibaba.dubbo.consumer.service

management:
  endpoints:
    web:
      exposure:
        include: "*"
